// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cscniqcndbbbezvaoboj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzY25pcWNuZGJiYmV6dmFvYm9qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzY3NDIsImV4cCI6MjA3MjIxMjc0Mn0.VAOyFJ8Rm9FEfNxteM9pXOlSG746xk4Mt1VMrnGcCQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});